# Generated by Django 5.0.2 on 2025-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0002_administradores_alumnos_maestros_delete_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_fin', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('publico_objetivo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_participantes', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
