# Generated by Django 5.0.2 on 2025-11-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0003_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='publico_objetivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
