# Generated by Django 5.0.2 on 2025-12-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0004_alter_evento_publico_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='programa_educativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
